	class ADFRC_MD_AMCU_Soldier_Base;
	class ADFRC_MD_AMCU_Soldier_Rolled_Base;
	class ADFRC_MD_AMCU_Soldier_Tee_Base;
	class ADFRC_MD_AMCU_Recon_Base;
	class ADFRC_MD_AMCU_Recon_Rolled_Base;
	class ADFRC_MD_AMCU_Sniper_Temperate_Base;
	class ADFRC_MD_AMCU_Sniper_Tropical_Base;
	class ADFRC_MD_AMCU_Sniper_Arid_Base;
	class ADFRC_MD_AMCU_CDO_Base;
	class ADFRC_MD_AMCU_CDO_Rolled_Base;
	class ADFRC_MD_AMCU_CDO_Tee_Base;
	////////////////////////Regular Units///////////////////////////////////////////////////////////
	class ADFRC_MD_AMCU_Soldier_F: ADFRC_MD_AMCU_Soldier_Base{
		displayName="Rifleman";
		author="$STR_ADF_AUTHOR";
		scope=2;
		scopeCurator=2;
		editorPreview = "\ADF_Units\data\editorPreviews\MD\AMCU_Soldier_F.jpg";
		role="Rifleman";
		//threat[]={0.80000001,0.1,0.1}; <---For us to tweak the threat it poses to other units https://community.bistudio.com/wiki/CfgVehicles_Config_Reference#threat 
		//backpack="ADFRC_AssaultPack_AMCU";
		weapons[]={
			"arifle_AUG_black_arco_flash_F",
			"ADFRC_hpII",
			"Throw",
			"Put"
		};
		respawnWeapons[]={
			"arifle_AUG_black_arco_flash_F",
			"ADFRC_hpII",
			"Throw",
			"Put"
		};
		magazines[]={
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"16Rnd_9x21_Mag",
			"SmokeShell",
			"SmokeShell",
			"ADFRC_F1_GRENADE",
			"ADFRC_F1_GRENADE"
		};
		respawnMagazines[]={
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"16Rnd_9x21_Mag",
			"SmokeShell",
			"SmokeShell",
			"ADFRC_F1_GRENADE",
			"ADFRC_F1_GRENADE"
		};
		linkedItems[]={
			"adfrc_opscore_marine_Snakeskin_amcu_Ct_1_Aus",
			"ADFRC_PC_Tan_1",
			"adfrc_facewear_ESS_1",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
		respawnLinkedItems[]={
			"adfrc_opscore_marine_Snakeskin_amcu_Ct_1_Aus",
			"ADFRC_PC_Tan_1",
			"adfrc_facewear_ESS_1",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
	};
	class ADFRC_MD_AMCU_Soldier_Grenadier: ADFRC_MD_AMCU_Soldier_Base{
		displayName="Grenadier";
		author="$STR_ADF_AUTHOR";
		scope=2;
		scopeCurator=2;
		editorPreview = "\ADF_Units\data\editorPreviews\MD\AMCU_Soldier_Grenadier.jpg";
		role="Grenadier";
		cost=200000;
		//threat[]={0.80000001,0.1,0.1}; <---For us to tweak the threat it poses to other units https://community.bistudio.com/wiki/CfgVehicles_Config_Reference#threat 
		//backpack="ADFRC_CarryAll_AMCU_GL";
		weapons[]={
			"arifle_AUG_GL_black_arco_flash_F",
			"ADFRC_hpII",
			"Throw",
			"Put"
		};
		respawnWeapons[]={
			"arifle_AUG_GL_black_arco_flash_F",
			"ADFRC_hpII",
			"Throw",
			"Put"
		};
		magazines[]={
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"16Rnd_9x21_Mag",
			"SmokeShell",
			"1Rnd_HE_Grenade_shell",
			"1Rnd_HE_Grenade_shell",
			"1Rnd_HE_Grenade_shell",
			"1Rnd_HE_Grenade_shell",
			"1Rnd_Smoke_Grenade_shell",
			"1Rnd_Smoke_Grenade_shell",
			"1Rnd_Smoke_Grenade_shell",
			"1Rnd_Smoke_Grenade_shell",
			"ADFRC_F1_GRENADE",
			"ADFRC_F1_GRENADE"
		};
		respawnMagazines[]={
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"16Rnd_9x21_Mag",
			"SmokeShell",
			"1Rnd_HE_Grenade_shell",
			"1Rnd_HE_Grenade_shell",
			"1Rnd_HE_Grenade_shell",
			"1Rnd_HE_Grenade_shell",
			"1Rnd_Smoke_Grenade_shell",
			"1Rnd_Smoke_Grenade_shell",
			"1Rnd_Smoke_Grenade_shell",
			"1Rnd_Smoke_Grenade_shell",
			"ADFRC_F1_GRENADE",
			"ADFRC_F1_GRENADE"
		};
		linkedItems[]={
			"adfrc_opscore_marine_Snakeskin_amcu_Ct_1_Aus",
			"ADFRC_PC_Tan_1",
			"adfrc_facewear_ESS_1",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
		respawnLinkedItems[]={
			"adfrc_opscore_marine_Snakeskin_amcu_Ct_1_Aus",
			"ADFRC_PC_Tan_1",
			"adfrc_facewear_ESS_1",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
	};
	class ADFRC_MD_AMCU_Soldier_LMG: ADFRC_MD_AMCU_Soldier_Rolled_Base{ // Rolled Sleeves
		displayName="LSW Gunner (Minimi)";
		author="$STR_ADF_AUTHOR";
		scope=2;
		scopeCurator=2;
		editorPreview = "\ADF_Units\data\editorPreviews\MD\AMCU_Soldier_LMG.jpg";
		class SpeechVariants{
			class Default{
				speechSingular[]={
					"veh_infantry_MG_s"
				};
				speechPlural[]={
					"veh_infantry_MG_p"
				};
			};
		};
		textSingular="$STR_A3_nameSound_veh_infantry_MG_s";
		textPlural="$STR_A3_nameSound_veh_infantry_MG_p";
		nameSound="veh_infantry_MG_s";
		icon="iconManMG";
		role="MachineGunner";
		cost=220000;
		//threat[]={0.80000001,0.1,0.1}; <---For us to tweak the threat it poses to other units https://community.bistudio.com/wiki/CfgVehicles_Config_Reference#threat 
		backpack="ADFRC_CarryAll_AMCU_LMG";
		weapons[]={
			"ADFRC_minimi_eotech",
			"ADFRC_hpII",
			"Throw",
			"Put"
		};
		respawnWeapons[]={
			"ADFRC_minimi_eotech",
			"ADFRC_hpII",
			"Throw",
			"Put"
		};
		magazines[]={
			"ADFRC_200Rnd_556_Belt_TR5",
			"ADFRC_200Rnd_556_Belt_TR5",
			"16Rnd_9x21_Mag",
			"SmokeShell",
			"SmokeShell",
			"ADFRC_F1_GRENADE",
			"ADFRC_F1_GRENADE"
		};
		respawnMagazines[]={
			"ADFRC_200Rnd_556_Belt_TR5",
			"ADFRC_200Rnd_556_Belt_TR5",
			"16Rnd_9x21_Mag",
			"SmokeShell",
			"SmokeShell",
			"ADFRC_F1_GRENADE",
			"ADFRC_F1_GRENADE"
		};
		linkedItems[]={
			"adfrc_opscore_marine_Snakeskin_amcu_Ct_1_Aus",
			"ADFRC_PC_Tan_1",
			"adfrc_facewear_ESS_1",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
		respawnLinkedItems[]={
			"adfrc_opscore_marine_Snakeskin_amcu_Ct_1_Aus",
			"ADFRC_PC_Tan_1",
			"adfrc_facewear_ESS_1",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
	};
	class ADFRC_MD_AMCU_Soldier_MMG: ADFRC_MD_AMCU_Soldier_Rolled_Base{ // Rolled Sleeves
		displayName="LSW Gunner (Maximi)";
		author="$STR_ADF_AUTHOR";
		scope=2;
		scopeCurator=2;
		editorPreview = "\ADF_Units\data\editorPreviews\MD\AMCU_Soldier_MMG.jpg";
		class SpeechVariants{
			class Default{
				speechSingular[]={
					"veh_infantry_MG_s"
				};
				speechPlural[]={
					"veh_infantry_MG_p"
				};
			};
		};
		textSingular="$STR_A3_nameSound_veh_infantry_MG_s";
		textPlural="$STR_A3_nameSound_veh_infantry_MG_p";
		nameSound="veh_infantry_MG_s";
		icon="iconManMG";
		role="MachineGunner";
		cost=220000;
		//threat[]={0.80000001,0.1,0.1}; <---For us to tweak the threat it poses to other units https://community.bistudio.com/wiki/CfgVehicles_Config_Reference#threat 
		backpack="ADFRC_CarryAll_AMCU_MMG";
		weapons[]={
			"ADFRC_minimi_eotech",
			"ADFRC_hpII",
			"Throw",
			"Put"
		};
		respawnWeapons[]={
			"ADFRC_minimi_eotech",
			"ADFRC_hpII",
			"Throw",
			"Put"
		};
		magazines[]={
			"ADFRC_200Rnd_556_Belt_TR5",
			"ADFRC_200Rnd_556_Belt_TR5",
			"16Rnd_9x21_Mag",
			"SmokeShell",
			"SmokeShell",
			"ADFRC_F1_GRENADE",
			"ADFRC_F1_GRENADE"
		};
		respawnMagazines[]={
			"ADFRC_200Rnd_556_Belt_TR5",
			"ADFRC_200Rnd_556_Belt_TR5",
			"16Rnd_9x21_Mag",
			"SmokeShell",
			"SmokeShell",
			"ADFRC_F1_GRENADE",
			"ADFRC_F1_GRENADE"
		};
		linkedItems[]={
			"adfrc_opscore_marine_Snakeskin_amcu_Ct_1_Aus",
			"ADFRC_PC_Tan_1",
			"adfrc_facewear_ESS_1",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
		respawnLinkedItems[]={
			"adfrc_opscore_marine_Snakeskin_amcu_Ct_1_Aus",
			"ADFRC_PC_Tan_1",
			"adfrc_facewear_ESS_1",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
	};
	class ADFRC_MD_AMCU_Soldier_GSMG: ADFRC_MD_AMCU_Soldier_Rolled_Base{ // Rolled Sleeves
		displayName="General Support Machine Gunner";
		author="$STR_ADF_AUTHOR";
		scope=2;
		scopeCurator=2;
		editorPreview = "\ADF_Units\data\editorPreviews\MD\AMCU_Soldier_GSMG.jpg";
		class SpeechVariants{
			class Default{
				speechSingular[]={
					"veh_infantry_MG_s"
				};
				speechPlural[]={
					"veh_infantry_MG_p"
				};
			};
		};
		textSingular="$STR_A3_nameSound_veh_infantry_MG_s";
		textPlural="$STR_A3_nameSound_veh_infantry_MG_p";
		nameSound="veh_infantry_MG_s";
		icon="iconManMG";
		role="MachineGunner";
		cost=220000;
		//threat[]={0.80000001,0.1,0.1}; <---For us to tweak the threat it poses to other units https://community.bistudio.com/wiki/CfgVehicles_Config_Reference#threat 
		//backpack="ADFRC_CarryAll_AMCU_GSMG";
		weapons[]={
			"ADFRC_mag58_elcan",
			"ADFRC_hpII",
			"Throw",
			"Put"
		};
		respawnWeapons[]={
			"ADFRC_mag58_elcan",
			"ADFRC_hpII",
			"Throw",
			"Put"
		};
		magazines[]={
			"ADFRC_150Rnd_762_Belt_TR5",
			"16Rnd_9x21_Mag",
			"SmokeShell",
			"SmokeShell",
			"ADFRC_F1_GRENADE",
			"ADFRC_F1_GRENADE"
		};
		respawnMagazines[]={
			"ADFRC_150Rnd_762_Belt_TR5",
			"16Rnd_9x21_Mag",
			"SmokeShell",
			"SmokeShell",
			"ADFRC_F1_GRENADE",
			"ADFRC_F1_GRENADE"
		};
		linkedItems[]={
			"adfrc_opscore_marine_Snakeskin_amcu_Ct_1_Aus",
			"ADFRC_PC_Tan_1",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
		respawnLinkedItems[]={
			"adfrc_opscore_marine_Snakeskin_amcu_Ct_1_Aus",
			"ADFRC_PC_Tan_1",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
	};
	class ADFRC_MD_AMCU_Soldier_Officer: ADFRC_MD_AMCU_Soldier_Base{
		displayName="Officer";
		author="$STR_ADF_AUTHOR";
		scope=2;
		scopeCurator=2;	
		editorPreview = "\ADF_Units\data\editorPreviews\MD\AMCU_Soldier_Officer.jpg";
		icon="iconManOfficer";
		role="Rifleman";
		cost=250000;
		camouflage=1.6;
		//threat[]={0.80000001,0.1,0.1}; <---For us to tweak the threat it poses to other units https://community.bistudio.com/wiki/CfgVehicles_Config_Reference#threat 
		weapons[]={
			"arifle_AUG_black_arco_flash_F",
			"ADFRC_hpII",
			"Throw",
			"Put",
			"Binocular"
		};
		respawnWeapons[]={
			"arifle_AUG_black_arco_flash_F",
			"ADFRC_hpII",
			"Throw",
			"Put",
			"Binocular"
		};
		magazines[]={
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"16Rnd_9x21_Mag",
			"ADFRC_F1_GRENADE",
			"ADFRC_F1_GRENADE",
			"SmokeShellPurple",
			"SmokeShellPurple",
			"SmokeShellRed",
			"SmokeShellRed",
			"SmokeShellOrange",
			"SmokeShellOrange"
		};
		respawnMagazines[]={
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"16Rnd_9x21_Mag",
			"ADFRC_F1_GRENADE",
			"ADFRC_F1_GRENADE",
			"SmokeShellPurple",
			"SmokeShellPurple",
			"SmokeShellRed",
			"SmokeShellRed",
			"SmokeShellOrange",
			"SmokeShellOrange"
		};
		linkedItems[]={
			"adfrc_opscore_marine_Snakeskin_amcu_Ct_1_Aus",
			"ADFRC_PC_Tan_1",
			"adfrc_facewear_ESS_1",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
		respawnLinkedItems[]={
			"adfrc_opscore_marine_Snakeskin_amcu_Ct_1_Aus",
			"ADFRC_PC_Tan_1",
			"adfrc_facewear_ESS_1",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
	};
	class ADFRC_MD_AMCU_Soldier_SectionComm: ADFRC_MD_AMCU_Soldier_Rolled_Base{ // Rolled Sleeves
		displayName="Section Commander";
		author="$STR_ADF_AUTHOR";
		scope=2;
		scopeCurator=2;	
		editorPreview = "\ADF_Units\data\editorPreviews\MD\AMCU_Soldier_SectionComm.jpg";
		icon="iconManLeader";
		role="Rifleman";
		cost=250000;
		camouflage=1.4;
		//threat[]={0.80000001,0.1,0.1}; <---For us to tweak the threat it poses to other units https://community.bistudio.com/wiki/CfgVehicles_Config_Reference#threat 
		//backpack="";
		weapons[]={
			"arifle_AUG_black_arco_flash_F",
			"ADFRC_hpII",
			"Throw",
			"Put",
			"Binocular"
		};
		respawnWeapons[]={
			"arifle_AUG_black_arco_flash_F",
			"ADFRC_hpII",
			"Throw",
			"Put",
			"Binocular"
		};
		magazines[]={
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"16Rnd_9x21_Mag",
			"ADFRC_F1_GRENADE",
			"ADFRC_F1_GRENADE",
			"SmokeShellPurple",
			"SmokeShellPurple",
			"SmokeShellRed",
			"SmokeShellRed",
			"SmokeShellOrange",
			"SmokeShellOrange"
		};
		respawnMagazines[]={
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"16Rnd_9x21_Mag",
			"ADFRC_F1_GRENADE",
			"ADFRC_F1_GRENADE",
			"SmokeShellPurple",
			"SmokeShellPurple",
			"SmokeShellRed",
			"SmokeShellRed",
			"SmokeShellOrange",
			"SmokeShellOrange"
		};
		linkedItems[]={
			"adfrc_opscore_marine_Snakeskin_amcu_Ct_1_Aus",
			"ADFRC_PC_Tan_1",
			"adfrc_facewear_ESS_1",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
		respawnLinkedItems[]={
			"adfrc_opscore_marine_Snakeskin_amcu_Ct_1_Aus",
			"ADFRC_PC_Tan_1",
			"adfrc_facewear_ESS_1",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
	};
	class ADFRC_MD_AMCU_Soldier_BrickComm: ADFRC_MD_AMCU_Soldier_Base{
		displayName="Brick Leader";
		author="$STR_ADF_AUTHOR";
		scope=2;
		scopeCurator=2;
		editorPreview = "\ADF_Units\data\editorPreviews\MD\AMCU_Soldier_BrickComm.jpg";
		icon="iconManLeader";
		role="Rifleman";
		cost=250000;
		camouflage=1.4;
		//threat[]={0.80000001,0.1,0.1}; <---For us to tweak the threat it poses to other units https://community.bistudio.com/wiki/CfgVehicles_Config_Reference#threat 
		//backpack="ADFRC_AssaultPack_AMCU";
		weapons[]={
			"arifle_AUG_black_arco_flash_F",
			"ADFRC_hpII",
			"Throw",
			"Put",
			"Binocular"
		};
		respawnWeapons[]={
			"arifle_AUG_black_arco_flash_F",
			"ADFRC_hpII",
			"Throw",
			"Put",
			"Binocular"
		};
		magazines[]={
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"16Rnd_9x21_Mag",
			"ADFRC_F1_GRENADE",
			"ADFRC_F1_GRENADE",
			"SmokeShell",
			"SmokeShell"
		};
		respawnMagazines[]={
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"16Rnd_9x21_Mag",
			"ADFRC_F1_GRENADE",
			"ADFRC_F1_GRENADE",
			"SmokeShell",
			"SmokeShell"
		};
		linkedItems[]={
			"adfrc_opscore_marine_Snakeskin_amcu_Ct_1_Aus",
			"ADFRC_PC_Tan_1",
			"adfrc_facewear_ESS_1",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
		respawnLinkedItems[]={
			"adfrc_opscore_marine_Snakeskin_amcu_Ct_1_Aus",
			"ADFRC_PC_Tan_1",
			"adfrc_facewear_ESS_1",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};	
	};
	class ADFRC_MD_AMCU_Soldier_Marksman: ADFRC_MD_AMCU_Soldier_Base{
		displayName="Designated Marksman";
		author="$STR_ADF_AUTHOR";
		scope=2;
		scopeCurator=2;
		editorPreview = "\ADF_Units\data\editorPreviews\MD\AMCU_Soldier_Marksman.jpg";
		class SpeechVariants{
			class Default{
				speechSingular[]={
					"veh_infantry_sniper_s"
				};
				speechPlural[]={
					"veh_infantry_sniper_p"
				};
			};
		};
		textSingular="$STR_A3_nameSound_veh_infantry_sniper_s";
		textPlural="$STR_A3_nameSound_veh_infantry_sniper_p";
		nameSound="veh_infantry_sniper_s";
		role="Marksman";
		cost=250000;
		//threat[]={0.80000001,0.1,0.1}; <---For us to tweak the threat it poses to other units https://community.bistudio.com/wiki/CfgVehicles_Config_Reference#threat 
		//backpack="";
		weapons[]={ // ADFRC_hk417_sand, ADFRC_acog_ta648_rds_t, acc_pointer_IR, 20Rnd_762x51_Mag
			"arifle_AUG_Elcan_Pointer_F",
			"ADFRC_hpII",
			"Throw",
			"Put",
			"Rangefinder"
		};
		respawnWeapons[]={
			"arifle_AUG_Elcan_Pointer_F",
			"ADFRC_hpII",
			"Throw",
			"Put",
			"Rangefinder"
		};
		magazines[]={
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"16Rnd_9x21_Mag",
			"ADFRC_F1_GRENADE",
			"ADFRC_F1_GRENADE",
			"SmokeShell",
			"SmokeShell"
		};
		respawnMagazines[]={
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"16Rnd_9x21_Mag",
			"ADFRC_F1_GRENADE",
			"ADFRC_F1_GRENADE",
			"SmokeShell",
			"SmokeShell"
		};
		linkedItems[]={
			"adfrc_opscore_marine_Snakeskin_amcu_Ct_1_Aus",
			"ADFRC_PC_Tan_1",
			"adfrc_facewear_ESS_1",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
		respawnLinkedItems[]={
			"adfrc_opscore_marine_Snakeskin_amcu_Ct_1_Aus",
			"ADFRC_PC_Tan_1",
			"adfrc_facewear_ESS_1",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
	};
	class ADFRC_MD_AMCU_Soldier_HATGunner: ADFRC_MD_AMCU_Soldier_Rolled_Base{ // Rolled Sleeves
		displayName="Rifleman (HAT)";
		author="$STR_ADF_AUTHOR";
		scope=2;
		scopeCurator=2;
		editorPreview = "\ADF_Units\data\editorPreviews\MD\AMCU_Soldier_HATGunner.jpg";
		class SpeechVariants{
			class Default{
				speechSingular[]={
					"veh_infantry_AT_s"
				};
				speechPlural[]={
					"veh_infantry_AT_p"
				};
			};
		};
		textSingular="$STR_A3_nameSound_veh_infantry_AT_s";
		textPlural="$STR_A3_nameSound_veh_infantry_AT_p";
		nameSound="veh_infantry_AT_s";
		icon="iconManAT";
		role="MissileSpecialist";
		cost=130000;
		camouflage=1.5;
		secondaryAmmoCoef=0.5;
		threat[]={0.80000001,0.80000001,0.30000001}; // From vanilla values
		backpack="ADFRC_CarryAll_AMCU_HAT";
		weapons[]={
			"arifle_AUG_black_arco_flash_F",
			"ADFRC_carlgustav_m3",
			"ADFRC_hpII",
			"Throw",
			"Put"
		};
		respawnWeapons[]={
			"arifle_AUG_black_arco_flash_F",
			"ADFRC_carlgustav_m3",
			"ADFRC_hpII",
			"Throw",
			"Put"
		};
		magazines[]={
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"16Rnd_9x21_Mag",
			"ADFRC_F1_GRENADE",
			"ADFRC_F1_GRENADE",
			"SmokeShell",
			"SmokeShell"
		};
		respawnMagazines[]={
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"16Rnd_9x21_Mag",
			"ADFRC_F1_GRENADE",
			"ADFRC_F1_GRENADE",
			"SmokeShell",
			"SmokeShell"
		};
		linkedItems[]={
			"adfrc_opscore_marine_Snakeskin_amcu_Ct_1_Aus",
			"ADFRC_PC_Tan_1",
			"adfrc_facewear_ESS_1",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
		respawnLinkedItems[]={
			"adfrc_opscore_marine_Snakeskin_amcu_Ct_1_Aus",
			"ADFRC_PC_Tan_1",
			"adfrc_facewear_ESS_1",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
	};
	class ADFRC_MD_AMCU_Soldier_MATGunner: ADFRC_MD_AMCU_Soldier_Rolled_Base{ // Rolled Sleeves
		displayName="Rifleman (MAT)";
		author="$STR_ADF_AUTHOR";
		scope=2;
		scopeCurator=2;
		editorPreview = "\ADF_Units\data\editorPreviews\MD\AMCU_Soldier_MATGunner.jpg";
		class SpeechVariants{
			class Default{
				speechSingular[]={
					"veh_infantry_AT_s"
				};
				speechPlural[]={
					"veh_infantry_AT_p"
				};
			};
		};
		textSingular="$STR_A3_nameSound_veh_infantry_AT_s";
		textPlural="$STR_A3_nameSound_veh_infantry_AT_p";
		nameSound="veh_infantry_AT_s";
		icon="iconManAT";
		role="MissileSpecialist";
		cost=130000;
		secondaryAmmoCoef=0.5;
		threat[]={0.80000001,0.80000001,0.30000001}; // From vanilla values
		backpack="ADFRC_CarryAll_AMCU_MAT";
		weapons[]={
			"arifle_AUG_black_arco_flash_F",
			"ADFRC_carlgustav_m3",
			"ADFRC_hpII",
			"Throw",
			"Put"
		};
		respawnWeapons[]=
		{
			"arifle_AUG_black_arco_flash_F",
			"ADFRC_carlgustav_m3",
			"ADFRC_hpII",
			"Throw",
			"Put",
			"Binocular"
		};
		magazines[]={
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"16Rnd_9x21_Mag",
			"ADFRC_F1_GRENADE",
			"ADFRC_F1_GRENADE",
			"SmokeShell",
			"SmokeShell"
		};
		respawnMagazines[]={
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"16Rnd_9x21_Mag",
			"ADFRC_F1_GRENADE",
			"ADFRC_F1_GRENADE",
			"SmokeShell",
			"SmokeShell"
		};
		linkedItems[]={
			"adfrc_opscore_marine_Snakeskin_amcu_Ct_1_Aus",
			"ADFRC_PC_Tan_1",
			"adfrc_facewear_ESS_1",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
		respawnLinkedItems[]={
			"adfrc_opscore_marine_Snakeskin_amcu_Ct_1_Aus",
			"ADFRC_PC_Tan_1",
			"adfrc_facewear_ESS_1",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
	};
	class ADFRC_MD_AMCU_Soldier_LATGunner: ADFRC_MD_AMCU_Soldier_Rolled_Base{ // Rolled Sleeves
		displayName="Rifleman (LAT)";
		author="$STR_ADF_AUTHOR";
		scope=2;
		scopeCurator=2;
		editorPreview = "\ADF_Units\data\editorPreviews\MD\AMCU_Soldier_LATGunner.jpg";
		class SpeechVariants{
			class Default{
				speechSingular[]={
					"veh_infantry_AT_s"
				};
				speechPlural[]={
					"veh_infantry_AT_p"
				};
			};
		};
		textSingular="$STR_A3_nameSound_veh_infantry_AT_s";
		textPlural="$STR_A3_nameSound_veh_infantry_AT_p";
		nameSound="veh_infantry_AT_s";
		icon="iconManAT";
		role="MissileSpecialist";
		cost=130000;
		secondaryAmmoCoef=0.5;
		threat[]={0.80000001,0.80000001,0.30000001}; // From vanilla values
		//backpack="";
		weapons[]={
			"arifle_AUG_black_arco_flash_F",
			"ADFRC_carlgustav_m3",
			"ADFRC_hpII",
			"Throw",
			"Put"
		};
		respawnWeapons[]={
			"arifle_AUG_black_arco_flash_F",
			"ADFRC_carlgustav_m3",
			"ADFRC_hpII",
			"Throw",
			"Put"
		};
		magazines[]={
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"16Rnd_9x21_Mag",
			"ADFRC_F1_GRENADE",
			"ADFRC_F1_GRENADE",
			"SmokeShell",
			"SmokeShell"
		};
		respawnMagazines[]={
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"16Rnd_9x21_Mag",
			"ADFRC_F1_GRENADE",
			"ADFRC_F1_GRENADE",
			"SmokeShell",
			"SmokeShell"
		};
		linkedItems[]={
			"adfrc_opscore_marine_Snakeskin_amcu_Ct_1_Aus",
			"ADFRC_PC_Tan_1",
			"adfrc_facewear_ESS_1",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
		respawnLinkedItems[]={
			"adfrc_opscore_marine_Snakeskin_amcu_Ct_1_Aus",
			"ADFRC_PC_Tan_1",
			"adfrc_facewear_ESS_1",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
	};
	class ADFRC_MD_AMCU_Soldier_CFA: ADFRC_MD_AMCU_Soldier_Rolled_Base{ // Rolled Sleeves
		displayName="Combat First Aider";
		author="$STR_ADF_AUTHOR";
		scope=2;
		scopeCurator=2;
		editorPreview = "\ADF_Units\data\editorPreviews\MD\AMCU_Soldier_CFA.jpg";
		class SpeechVariants{
			class Default{
				speechSingular[]={
					"veh_infantry_medic_s"
				};
				speechPlural[]={
					"veh_infantry_medic_p"
				};
			};
		};
		textSingular="$STR_A3_nameSound_veh_infantry_medic_s";
		textPlural="$STR_A3_nameSound_veh_infantry_medic_p";
		nameSound="veh_infantry_medic_s";
		icon="iconManMedic";
		role="CombatLifeSaver";
		picture="pictureHeal";
		attendant=1;
		camouflage=1.6;
		//threat[]={0.80000001,0.1,0.1}; <---For us to tweak the threat it poses to other units https://community.bistudio.com/wiki/CfgVehicles_Config_Reference#threat 
		backpack="ADFRC_CarryAll_AMCU_MED_CFA";
		weapons[]={
			"arifle_AUG_black_arco_flash_F",
			"ADFRC_hpII",
			"Throw",
			"Put"
		};
		respawnWeapons[]={
			"arifle_AUG_black_arco_flash_F",
			"ADFRC_hpII",
			"Throw",
			"Put"
		};
		magazines[]={
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"16Rnd_9x21_Mag",
			"SmokeShell",
			"SmokeShell",
			"ADFRC_F1_GRENADE",
			"ADFRC_F1_GRENADE"
		};
		respawnMagazines[]={
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"16Rnd_9x21_Mag",
			"SmokeShell",
			"SmokeShell",
			"ADFRC_F1_GRENADE",
			"ADFRC_F1_GRENADE"
		};
		linkedItems[]={
			"adfrc_opscore_marine_Snakeskin_amcu_Ct_1_Aus",
			"ADFRC_PC_Tan_1",
			"adfrc_facewear_ESS_1",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
		respawnLinkedItems[]={
			"adfrc_opscore_marine_Snakeskin_amcu_Ct_1_Aus",
			"ADFRC_PC_Tan_1",
			"adfrc_facewear_ESS_1",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};	
	};
	class ADFRC_MD_AMCU_Soldier_Engineer: ADFRC_MD_AMCU_Soldier_Rolled_Base{ // Rolled Sleeves
		displayName="Combat Engineer";
		author="$STR_ADF_AUTHOR";
		scope=2;
		scopeCurator=2;
		editorPreview = "\ADF_Units\data\editorPreviews\MD\AMCU_Soldier_Engineer.jpg";
		icon="iconManExplosive";
		role="Sapper";
		picture="pictureExplosive";
		cost=93000;
		camouflage=1.6;
		engineer=1;
		canDeactivateMines=1;
		detectSkill=38;
		//threat[]={0.80000001,0.1,0.1}; <---For us to tweak the threat it poses to other units https://community.bistudio.com/wiki/CfgVehicles_Config_Reference#threat 
		backpack="ADFRC_CarryAll_AMCU_Engineer";
		weapons[]={
			"arifle_AUG_black_arco_flash_F",
			"ADFRC_hpII",
			"Throw",
			"Put"
		};
		respawnWeapons[]={
			"arifle_AUG_black_arco_flash_F",
			"ADFRC_hpII",
			"Throw",
			"Put"
		};
		magazines[]={
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"16Rnd_9x21_Mag",
			"SmokeShell",
			"SmokeShell",
			"ADFRC_F1_GRENADE",
			"ADFRC_F1_GRENADE"
		};
		respawnMagazines[]={
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"16Rnd_9x21_Mag",
			"SmokeShell",
			"SmokeShell",
			"ADFRC_F1_GRENADE",
			"ADFRC_F1_GRENADE"
		};
		linkedItems[]={
			"adfrc_opscore_marine_Snakeskin_amcu_Ct_1_Aus",
			"ADFRC_PC_Tan_1",
			"adfrc_facewear_ESS_1",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
		respawnLinkedItems[]={
			"adfrc_opscore_marine_Snakeskin_amcu_Ct_1_Aus",
			"ADFRC_PC_Tan_1",
			"adfrc_facewear_ESS_1",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
	};
	class ADFRC_MD_AMCU_Soldier_Mine: ADFRC_MD_AMCU_Soldier_Rolled_Base{ // Rolled Sleeves
		displayName="Mine Specialist";
		author="$STR_ADF_AUTHOR";
		scope=2;
		scopeCurator=2;
		editorPreview = "\ADF_Units\data\editorPreviews\MD\AMCU_Soldier_Mine.jpg";
		icon="iconManExplosive";
		role="Sapper";
		picture="pictureExplosive";
		cost=93000;
		camouflage=1.6;
		canDeactivateMines=1;
		detectSkill=38;
		//threat[]={0.80000001,0.1,0.1}; <---For us to tweak the threat it poses to other units https://community.bistudio.com/wiki/CfgVehicles_Config_Reference#threat 
		backpack="ADFRC_CarryAll_AMCU_Mine";
		weapons[]={
			"arifle_AUG_black_arco_flash_F",
			"ADFRC_hpII",
			"Throw",
			"Put"
		};
		respawnWeapons[]={
			"arifle_AUG_black_arco_flash_F",
			"ADFRC_hpII",
			"Throw",
			"Put"
		};
		magazines[]={
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"16Rnd_9x21_Mag",
			"SmokeShell",
			"SmokeShell",
			"ADFRC_F1_GRENADE",
			"ADFRC_F1_GRENADE"
		};
		respawnMagazines[]={
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"16Rnd_9x21_Mag",
			"SmokeShell",
			"SmokeShell",
			"ADFRC_F1_GRENADE",
			"ADFRC_F1_GRENADE"
		};
		linkedItems[]={
			"adfrc_opscore_marine_Snakeskin_amcu_Ct_1_Aus",
			"ADFRC_PC_Tan_1",
			"adfrc_facewear_ESS_1",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
		respawnLinkedItems[]={
			"adfrc_opscore_marine_Snakeskin_amcu_Ct_1_Aus",
			"ADFRC_PC_Tan_1",
			"adfrc_facewear_ESS_1",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
	};
	class ADFRC_MD_AMCU_Soldier_HeliPilot: ADFRC_MD_AMCU_Soldier_Base{
		displayName="Helicopter Pilot";
		author="$STR_ADF_AUTHOR";
		scope=2;
		scopeCurator=2;
		editorPreview = "\ADF_Units\data\editorPreviews\MD\AMCU_Soldier_HeliPilot.jpg";
		class SpeechVariants{
			class Default{
				speechSingular[]={
					"veh_infantry_pilot_s"
				};
				speechPlural[]={
					"veh_infantry_pilot_p"
				};
			};
		};
		textSingular="$STR_A3_nameSound_veh_infantry_pilot_s";
		textPlural="$STR_A3_nameSound_veh_infantry_pilot_p";
		nameSound="veh_infantry_pilot_s";
		role="Crewman";
		camouflage=2;
		cost=93000;
		armor=2;
		armorStructural=2;
		explosionShielding=0.2;
		uniformClass="U_B_HeliPilotCoveralls";
		//threat[]={0.80000001,0.1,0.1}; <---For us to tweak the threat it poses to other units https://community.bistudio.com/wiki/CfgVehicles_Config_Reference#threat 
		//backpack="";
		weapons[]={
			"ADFRC_hpII",
			"Throw",
			"Put"
		};
		respawnWeapons[]={
			"ADFRC_hpII",
			"Throw",
			"Put"
		};
		magazines[]={
			"16Rnd_9x21_Mag",
			"16Rnd_9x21_Mag",
			"ADFRC_F1_GRENADE",
			"ADFRC_F1_GRENADE",
			"SmokeShell",
			"SmokeShellRed",
			"SmokeShellPurple"
		};
		respawnMagazines[]={
			"16Rnd_9x21_Mag",
			"16Rnd_9x21_Mag",
			"ADFRC_F1_GRENADE",
			"ADFRC_F1_GRENADE",
			"SmokeShell",
			"SmokeShellRed",
			"SmokeShellPurple"
		};
		linkedItems[]={
			"H_PilotHelmetHeli_O",
			"V_TacVest_khk",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
		respawnLinkedItems[]={
			"H_PilotHelmetHeli_O",
			"V_TacVest_khk",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
	};
	class ADFRC_MD_AMCU_Soldier_HeliCrew: ADFRC_MD_AMCU_Soldier_HeliPilot{
		displayName="Helicopter Crew";
		author="$STR_ADF_AUTHOR";
		scope=2;
		scopeCurator=2;
		editorPreview = "\ADF_Units\data\editorPreviews\MD\AMCU_Soldier_HeliCrew.jpg";
		uniformClass="U_B_HeliPilotCoveralls";
		weapons[]={
			"ADFRC_hpII",
			"Throw",
			"Put"
		};
		respawnWeapons[]={
			"ADFRC_hpII",
			"Throw",
			"Put"
		};
		magazines[]={
			"16Rnd_9x21_Mag",
			"16Rnd_9x21_Mag",
			"ADFRC_F1_GRENADE",
			"ADFRC_F1_GRENADE",
			"SmokeShell",
			"SmokeShellRed",
			"SmokeShellPurple"
		};
		respawnMagazines[]={
			"16Rnd_9x21_Mag",
			"16Rnd_9x21_Mag",
			"ADFRC_F1_GRENADE",
			"ADFRC_F1_GRENADE",
			"SmokeShell",
			"SmokeShellRed",
			"SmokeShellPurple"
		};
		linkedItems[]={
			"H_CrewHelmetHeli_O",
			"V_TacVest_khk",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
		respawnLinkedItems[]={
			"H_CrewHelmetHeli_O",
			"V_TacVest_khk",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
	};
	class ADFRC_MD_AMCU_Soldier_Crewman: ADFRC_MD_AMCU_Soldier_Base{
		displayName="Crewman";
		author="$STR_ADF_AUTHOR";
		scope=2;
		scopeCurator=2;
		editorPreview = "\ADF_Units\data\editorPreviews\MD\AMCU_Soldier_Crewman.jpg";
		role="Crewman";
		cost=93000;
		camouflage=1.6;
		//threat[]={0.80000001,0.1,0.1}; <---For us to tweak the threat it poses to other units https://community.bistudio.com/wiki/CfgVehicles_Config_Reference#threat 
		//backpack="";
		weapons[]={
			"arifle_AUG_C_black_F",
			"ADFRC_hpII",
			"Throw",
			"Put",
			"Binocular"
		};
		respawnWeapons[]={
			"arifle_AUG_C_black_F",
			"ADFRC_hpII",
			"Throw",
			"Put",
			"Binocular"
		};
		magazines[]={
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"16Rnd_9x21_Mag",
			"ADFRC_F1_GRENADE",
			"ADFRC_F1_GRENADE",
			"SmokeShell",
			"SmokeShell"
		};
		respawnMagazines[]={
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"16Rnd_9x21_Mag",
			"ADFRC_F1_GRENADE",
			"ADFRC_F1_GRENADE",
			"SmokeShell",
			"SmokeShell"
		};
		linkedItems[]={
			"H_HelmetCrew_I",
			"ADFRC_LPC_Tan_1",
			"adfrc_facewear_Shemagh_cbr_gatorz_1",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
		respawnLinkedItems[]={
			"H_HelmetCrew_I",
			"ADFRC_LPC_Tan_1",
			"adfrc_facewear_Shemagh_cbr_gatorz_1",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
	};
	class ADFRC_MD_AMCU_Soldier_CavalryScout: ADFRC_MD_AMCU_Soldier_Base{
		displayName="Cavalry Scout";
		author="$STR_ADF_AUTHOR";
		scope=2;
		scopeCurator=2;
		editorPreview = "\ADF_Units\data\editorPreviews\MD\AMCU_Soldier_CavalryScout.jpg";
		role="Rifleman";
		threat[]={0.70000001,0.1,0.1};
		//threat[]={0.80000001,0.1,0.1}; <---For us to tweak the threat it poses to other units https://community.bistudio.com/wiki/CfgVehicles_Config_Reference#threat 
		//backpack="";
		weapons[]={
			"arifle_AUG_C_black_F",
			"ADFRC_hpII",
			"Throw",
			"Put",
			"Binocular"
		};
		respawnWeapons[]={
			"arifle_AUG_C_black_F",
			"ADFRC_hpII",
			"Throw",
			"Put",
			"Binocular"
		};
		magazines[]={
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"16Rnd_9x21_Mag",
			"ADFRC_F1_GRENADE",
			"ADFRC_F1_GRENADE",
			"SmokeShell",
			"SmokeShell"
		};
		respawnMagazines[]={
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"16Rnd_9x21_Mag",
			"ADFRC_F1_GRENADE",
			"ADFRC_F1_GRENADE",
			"SmokeShell",
			"SmokeShell"
		};
		linkedItems[]={
			"H_Cap_headphones",
			"ADFRC_LPC_Tan_2",
			"adfrc_facewear_kondor_blk_blk",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
		respawnLinkedItems[]={
			"H_Cap_headphones",
			"ADFRC_LPC_Tan_2",
			"adfrc_facewear_kondor_blk_blk",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
	};	
	class ADFRC_MD_AMCU_Soldier_AmmoBearer: ADFRC_MD_AMCU_Soldier_Rolled_Base{ // Rolled Sleeves
		displayName="Ammobearer";
		author="$STR_ADF_AUTHOR";
		scope=2;
		scopeCurator=2;
		editorPreview = "\ADF_Units\data\editorPreviews\MD\AMCU_Soldier_AmmoBearer.jpg";
		role="Rifleman";
		camouflage=1.5;
		//threat[]={0.80000001,0.1,0.1}; <---For us to tweak the threat it poses to other units https://community.bistudio.com/wiki/CfgVehicles_Config_Reference#threat 
		//backpack="ADFRC_CarryAll_AMCU_AB";
		weapons[]={
			"arifle_AUG_black_arco_flash_F",
			"ADFRC_hpII",
			"Throw",
			"Put"
		};
		respawnWeapons[]={
			"arifle_AUG_black_arco_flash_F",
			"ADFRC_hpII",
			"Throw",
			"Put"
		};
		magazines[]={
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"16Rnd_9x21_Mag",
			"16Rnd_9x21_Mag",
			"ADFRC_F1_GRENADE",
			"ADFRC_F1_GRENADE",
			"SmokeShell",
			"SmokeShell"
		};
		respawnMagazines[]={
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"16Rnd_9x21_Mag",
			"16Rnd_9x21_Mag",
			"ADFRC_F1_GRENADE",
			"ADFRC_F1_GRENADE",
			"SmokeShell",
			"SmokeShell"
		};
		linkedItems[]={
			"adfrc_ECH_amcu",
			"ADFRC_carrierLite_amcu",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
		respawnLinkedItems[]={
			"adfrc_ECH_amcu",
			"ADFRC_carrierLite_amcu",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
	};
	class ADFRC_MD_AMCU_Soldier_GSMGAsst: ADFRC_MD_AMCU_Soldier_Rolled_Base{ // Rolled Sleeves
		displayName="General Support Gunner Assistant";
		author="$STR_ADF_AUTHOR";
		scope=2;
		scopeCurator=2;
		editorPreview = "\ADF_Units\data\editorPreviews\MD\AMCU_Soldier_GSMGAsst.jpg";
		role="Rifleman";
		camouflage=1.5;
		//threat[]={0.80000001,0.1,0.1}; <---For us to tweak the threat it poses to other units https://community.bistudio.com/wiki/CfgVehicles_Config_Reference#threat 
		backpack="ADFRC_CarryAll_AMCU_GSMG";
		weapons[]={
			"arifle_AUG_black_arco_flash_F",
			"ADFRC_hpII",
			"Throw",
			"Put"
		};
		respawnWeapons[]={
			"arifle_AUG_black_arco_flash_F",
			"ADFRC_hpII",
			"Throw",
			"Put"
		};
		magazines[]={
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"16Rnd_9x21_Mag",
			"SmokeShell",
			"SmokeShell",
			"ADFRC_F1_GRENADE",
			"ADFRC_F1_GRENADE"
		};
		respawnMagazines[]={
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"16Rnd_9x21_Mag",
			"SmokeShell",
			"SmokeShell",
			"ADFRC_F1_GRENADE",
			"ADFRC_F1_GRENADE"
		};
		linkedItems[]={
			"adfrc_opscore_marine_Snakeskin_amcu_Ct_1_Aus",
			"ADFRC_PC_Tan_1",
			"adfrc_facewear_ESS_1",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
		respawnLinkedItems[]={
			"adfrc_opscore_marine_Snakeskin_amcu_Ct_1_Aus",
			"ADFRC_PC_Tan_1",
			"adfrc_facewear_ESS_1",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
	};
	class ADFRC_MD_AMCU_Soldier_HATAsst: ADFRC_MD_AMCU_Soldier_Rolled_Base{ // Rolled Sleeves
		displayName="Rifleman (HAT Asst.)";
		author="$STR_ADF_AUTHOR";
		scope=2;
		scopeCurator=2;
		editorPreview = "\ADF_Units\data\editorPreviews\MD\AMCU_Soldier_HATAsst.jpg";
		role="Rifleman";
		camouflage=1.5;
		//threat[]={0.80000001,0.1,0.1}; <---For us to tweak the threat it poses to other units https://community.bistudio.com/wiki/CfgVehicles_Config_Reference#threat 
		//backpack="ADFRC_CarryAll_AMCU_HAT";
		weapons[]={
			"arifle_AUG_black_arco_flash_F",
			"ADFRC_hpII",
			"Throw",
			"Put"
		};
		respawnWeapons[]={
			"arifle_AUG_black_arco_flash_F",
			"ADFRC_hpII",
			"Throw",
			"Put"
		};
		magazines[]={
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"16Rnd_9x21_Mag",
			"16Rnd_9x21_Mag",
			"ADFRC_F1_GRENADE",
			"ADFRC_F1_GRENADE",
			"SmokeShell",
			"SmokeShell"
		};
		respawnMagazines[]={
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"16Rnd_9x21_Mag",
			"16Rnd_9x21_Mag",
			"ADFRC_F1_GRENADE",
			"ADFRC_F1_GRENADE",
			"SmokeShell",
			"SmokeShell"
		};
		linkedItems[]={
			"adfrc_ECH_amcu",
			"ADFRC_carrierLite_amcu",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
		respawnLinkedItems[]={
			"adfrc_ECH_amcu",
			"ADFRC_carrierLite_amcu",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
	};
	class ADFRC_MD_AMCU_Soldier_MATAsst: ADFRC_MD_AMCU_Soldier_Rolled_Base{ // Rolled Sleeves
		displayName="Rifleman (MAT Asst.)";
		author="$STR_ADF_AUTHOR";
		scope=2;
		scopeCurator=2;
		editorPreview = "\ADF_Units\data\editorPreviews\MD\AMCU_Soldier_MATAsst.jpg";
		role="Rifleman";
		camouflage=1.5;
		//threat[]={0.80000001,0.1,0.1}; <---For us to tweak the threat it poses to other units https://community.bistudio.com/wiki/CfgVehicles_Config_Reference#threat 
		//backpack="ADFRC_CarryAll_AMCU_MAT";
		weapons[]={
			"arifle_AUG_black_arco_flash_F",
			"ADFRC_hpII",
			"Throw",
			"Put"
		};
		respawnWeapons[]={
			"arifle_AUG_black_arco_flash_F",
			"ADFRC_hpII",
			"Throw",
			"Put"
		};
		magazines[]={
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"16Rnd_9x21_Mag",
			"16Rnd_9x21_Mag",
			"ADFRC_F1_GRENADE",
			"ADFRC_F1_GRENADE",
			"SmokeShell",
			"SmokeShell"
		};
		respawnMagazines[]={
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"16Rnd_9x21_Mag",
			"16Rnd_9x21_Mag",
			"ADFRC_F1_GRENADE",
			"ADFRC_F1_GRENADE",
			"SmokeShell",
			"SmokeShell"
		};
		linkedItems[]={
			"adfrc_ECH_amcu",
			"ADFRC_carrierLite_amcu",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
		respawnLinkedItems[]={
			"adfrc_ECH_amcu",
			"ADFRC_carrierLite_amcu",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
	};
	class ADFRC_MD_AMCU_Soldier_MMGAsst: ADFRC_MD_AMCU_Soldier_Rolled_Base{ // Rolled Sleeves
		displayName="Rifleman (MMG Asst.)";
		author="$STR_ADF_AUTHOR";
		scope=2;
		scopeCurator=2;
		editorPreview = "\ADF_Units\data\editorPreviews\MD\AMCU_Soldier_MMGAsst.jpg";
		role="Rifleman";
		camouflage=1.5;
		//threat[]={0.80000001,0.1,0.1}; <---For us to tweak the threat it poses to other units https://community.bistudio.com/wiki/CfgVehicles_Config_Reference#threat 
		//backpack="ADFRC_CarryAll_AMCU_MMG";
		weapons[]={
			"arifle_AUG_black_arco_flash_F",
			"ADFRC_hpII",
			"Throw",
			"Put"
		};
		respawnWeapons[]={
			"arifle_AUG_black_arco_flash_F",
			"ADFRC_hpII",
			"Throw",
			"Put"
		};
		magazines[]={
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"16Rnd_9x21_Mag",
			"16Rnd_9x21_Mag",
			"ADFRC_F1_GRENADE",
			"ADFRC_F1_GRENADE",
			"SmokeShell",
			"SmokeShell"
		};
		respawnMagazines[]={
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"16Rnd_9x21_Mag",
			"16Rnd_9x21_Mag",
			"ADFRC_F1_GRENADE",
			"ADFRC_F1_GRENADE",
			"SmokeShell",
			"SmokeShell"
		};
		linkedItems[]={
			"adfrc_ECH_amcu",
			"ADFRC_carrierLite_amcu",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
		respawnLinkedItems[]={
			"adfrc_ECH_amcu",
			"ADFRC_carrierLite_amcu",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
	};
	class ADFRC_MD_AMCU_Soldier_Shotgun: ADFRC_MD_AMCU_Soldier_Base{
		displayName="Rifleman (870)";
		author="$STR_ADF_AUTHOR";
		scope=1;
		scopeCurator=1;
		editorPreview = "\ADF_Units\data\editorPreviews\MD\AMCU_Soldier_Shotgun.jpg";
		role="Rifleman";
		camouflage=1.5;
		//threat[]={0.80000001,0.1,0.1}; <---For us to tweak the threat it poses to other units https://community.bistudio.com/wiki/CfgVehicles_Config_Reference#threat 
		//backpack="";
		weapons[]={
			"arifle_AUG_black_arco_flash_F",
			"ADFRC_hpII",
			"Throw",
			"Put"
		};
		respawnWeapons[]={
			"arifle_AUG_black_arco_flash_F",
			"ADFRC_hpII",
			"Throw",
			"Put"
		};
		magazines[]={
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"16Rnd_9x21_Mag",
			"SmokeShell",
			"SmokeShell",
			"ADFRC_F1_GRENADE",
			"ADFRC_F1_GRENADE"
		};
		respawnMagazines[]={
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"16Rnd_9x21_Mag",
			"SmokeShell",
			"SmokeShell",
			"ADFRC_F1_GRENADE",
			"ADFRC_F1_GRENADE"
		};
		linkedItems[]={
			"adfrc_opscore_marine_Snakeskin_amcu_Ct_1_Aus",
			"ADFRC_PC_Tan_1",
			"adfrc_facewear_ESS_1",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
		respawnLinkedItems[]={
			"adfrc_opscore_marine_Snakeskin_amcu_Ct_1_Aus",
			"ADFRC_PC_Tan_1",
			"adfrc_facewear_ESS_1",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
	};
	class ADFRC_MD_AMCU_Soldier_Unarmed: ADFRC_MD_AMCU_Soldier_Tee_Base{
		displayName="Rifleman (Unarmed)";
		author="$STR_ADF_AUTHOR";
		scope=2;
		scopeCurator=2;
		editorPreview = "\ADF_Units\data\editorPreviews\MD\AMCU_Soldier_Unarmed.jpg";
		role="Unarmed";
		threat[]={0.1,0.1,0.1}; // From vanilla values
		weapons[]={
			"Throw",
			"Put"
		};
		respawnWeapons[]={
			"Throw",
			"Put"
		};
		magazines[]={};
		respawnMagazines[]={};
		linkedItems[]={
			"adfrc_opscore_marine_Snakeskin_amcu_Ct_1_Aus",
			"ADFRC_PC_Tan_1",
			"adfrc_facewear_ESS_1",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
		respawnLinkedItems[]={
			"adfrc_opscore_marine_Snakeskin_amcu_Ct_1_Aus",
			"ADFRC_PC_Tan_1",
			"adfrc_facewear_ESS_1",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
	};
	////////////////////////Support Units///////////////////////////////////////////////////////////
	class ADFRC_MD_AMCU_Support_AMor: ADFRC_MD_AMCU_Soldier_Base{
		displayName="Asst. Gunner (Mortar)";
		author="$STR_ADF_AUTHOR";
		scope=2;
		scopeCurator=2;
		editorPreview = "\ADF_Units\data\editorPreviews\MD\AMCU_Support_AMor.jpg";
		role="Assistant";
		cost=220000;
		camouflage=1.5;
		//threat[]={0.80000001,0.1,0.1}; <---For us to tweak the threat it poses to other units https://community.bistudio.com/wiki/CfgVehicles_Config_Reference#threat
		backpack="B_Mortar_01_support_F";
		weapons[]={
			"arifle_AUG_black_arco_flash_F",
			"ADFRC_hpII",
			"Throw",
			"Put"
		};
		respawnWeapons[]={
			"arifle_AUG_black_arco_flash_F",
			"ADFRC_hpII",
			"Throw",
			"Put"
		};
		magazines[]={
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"16Rnd_9x21_Mag",
			"SmokeShell",
			"SmokeShell",
			"ADFRC_F1_GRENADE",
			"ADFRC_F1_GRENADE"
		};
		respawnMagazines[]={
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"16Rnd_9x21_Mag",
			"SmokeShell",
			"SmokeShell",
			"ADFRC_F1_GRENADE",
			"ADFRC_F1_GRENADE"
		};
		linkedItems[]={
			"adfrc_opscore_marine_Snakeskin_amcu_Ct_1_Aus",
			"ADFRC_PC_Tan_1",
			"adfrc_facewear_ESS_1",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
		respawnLinkedItems[]={
			"adfrc_opscore_marine_Snakeskin_amcu_Ct_1_Aus",
			"ADFRC_PC_Tan_1",
			"adfrc_facewear_ESS_1",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
	};
	class ADFRC_MD_AMCU_Support_AMG: ADFRC_MD_AMCU_Soldier_Base{
		displayName="Asst. Gunner (HMG/GMG)";
		author="$STR_ADF_AUTHOR";
		scope=2;
		scopeCurator=2;
		editorPreview = "\ADF_Units\data\editorPreviews\MD\AMCU_Support_AMG.jpg";
		role="Assistant";
		cost=220000;
		camouflage=1.5;
		//threat[]={0.80000001,0.1,0.1}; <---For us to tweak the threat it poses to other units https://community.bistudio.com/wiki/CfgVehicles_Config_Reference#threat
		backpack="adfrc_CarryAll_amc";
		weapons[]={
			"arifle_AUG_black_arco_flash_F",
			"ADFRC_hpII",
			"Throw",
			"Put"
		};
		respawnWeapons[]={
			"arifle_AUG_black_arco_flash_F",
			"ADFRC_hpII",
			"Throw",
			"Put"
		};
		magazines[]={
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"16Rnd_9x21_Mag",
			"SmokeShell",
			"SmokeShell",
			"ADFRC_F1_GRENADE",
			"ADFRC_F1_GRENADE"
		};
		respawnMagazines[]={
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"16Rnd_9x21_Mag",
			"SmokeShell",
			"SmokeShell",
			"ADFRC_F1_GRENADE",
			"ADFRC_F1_GRENADE"
		};
		linkedItems[]={
			"adfrc_opscore_marine_Snakeskin_amcu_Ct_1_Aus",
			"ADFRC_PC_Tan_1",
			"adfrc_facewear_ESS_1",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
		respawnLinkedItems[]={
			"adfrc_opscore_marine_Snakeskin_amcu_Ct_1_Aus",
			"ADFRC_PC_Tan_1",
			"adfrc_facewear_ESS_1",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
	};
	class ADFRC_MD_AMCU_Support_GMG: ADFRC_MD_AMCU_Soldier_Base{
		displayName="Gunner (GMG)";
		author="$STR_ADF_AUTHOR";
		scope=2;
		scopeCurator=2;
		editorPreview = "\ADF_Units\data\editorPreviews\MD\AMCU_Support_GMG.jpg";
		role="Assistant";
		cost=220000;
		camouflage=1.5;
		//threat[]={0.80000001,0.1,0.1}; <---For us to tweak the threat it poses to other units https://community.bistudio.com/wiki/CfgVehicles_Config_Reference#threat
		backpack="adfrc_CarryAll_amc";
		weapons[]={
			"arifle_AUG_black_arco_flash_F",
			"ADFRC_hpII",
			"Throw",
			"Put"
		};
		respawnWeapons[]={
			"arifle_AUG_black_arco_flash_F",
			"ADFRC_hpII",
			"Throw",
			"Put"
		};
		magazines[]={
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"16Rnd_9x21_Mag",
			"SmokeShell",
			"SmokeShell",
			"ADFRC_F1_GRENADE",
			"ADFRC_F1_GRENADE"
		};
		respawnMagazines[]={
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"16Rnd_9x21_Mag",
			"SmokeShell",
			"SmokeShell",
			"ADFRC_F1_GRENADE",
			"ADFRC_F1_GRENADE"
		};
		linkedItems[]={
			"adfrc_opscore_marine_Snakeskin_amcu_Ct_1_Aus",
			"ADFRC_PC_Tan_1",
			"adfrc_facewear_ESS_1",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
		respawnLinkedItems[]={
			"adfrc_opscore_marine_Snakeskin_amcu_Ct_1_Aus",
			"ADFRC_PC_Tan_1",
			"adfrc_facewear_ESS_1",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
	};
	class ADFRC_MD_AMCU_Support_HMG: ADFRC_MD_AMCU_Soldier_Base{
		displayName="Gunner (HMG)";
		author="$STR_ADF_AUTHOR";
		scope=2;
		scopeCurator=2;
		editorPreview = "\ADF_Units\data\editorPreviews\MD\AMCU_Support_HMG.jpg";
		role="Assistant";
		cost=220000;
		camouflage=1.5;
		//threat[]={0.80000001,0.1,0.1}; <---For us to tweak the threat it poses to other units https://community.bistudio.com/wiki/CfgVehicles_Config_Reference#threat
		backpack="adfrc_CarryAll_amc";
		weapons[]={
			"arifle_AUG_black_arco_flash_F",
			"ADFRC_hpII",
			"Throw",
			"Put"
		};
		respawnWeapons[]={
			"arifle_AUG_black_arco_flash_F",
			"ADFRC_hpII",
			"Throw",
			"Put"
		};
		magazines[]={
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"16Rnd_9x21_Mag",
			"SmokeShell",
			"SmokeShell",
			"ADFRC_F1_GRENADE",
			"ADFRC_F1_GRENADE"
		};
		respawnMagazines[]={
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"16Rnd_9x21_Mag",
			"SmokeShell",
			"SmokeShell",
			"ADFRC_F1_GRENADE",
			"ADFRC_F1_GRENADE"
		};
		linkedItems[]={
			"adfrc_opscore_marine_Snakeskin_amcu_Ct_1_Aus",
			"ADFRC_PC_Tan_1",
			"adfrc_facewear_ESS_1",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
		respawnLinkedItems[]={
			"adfrc_opscore_marine_Snakeskin_amcu_Ct_1_Aus",
			"ADFRC_PC_Tan_1",
			"adfrc_facewear_ESS_1",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
	};
	class ADFRC_MD_AMCU_Support_Mort: ADFRC_MD_AMCU_Soldier_Base{
		displayName="Gunner (Mortar)";
		author="$STR_ADF_AUTHOR";
		scope=2;
		scopeCurator=2;
		editorPreview = "\ADF_Units\data\editorPreviews\MD\AMCU_Support_Mort.jpg";
		role="Assistant";
		cost=220000;
		camouflage=1.5;
		//threat[]={0.80000001,0.1,0.1}; <---For us to tweak the threat it poses to other units https://community.bistudio.com/wiki/CfgVehicles_Config_Reference#threat
		backpack="B_Mortar_01_weapon_F";
		weapons[]={
			"arifle_AUG_black_arco_flash_F",
			"ADFRC_hpII",
			"Throw",
			"Put"
		};
		respawnWeapons[]={
			"arifle_AUG_black_arco_flash_F",
			"ADFRC_hpII",
			"Throw",
			"Put"
		};
		magazines[]={
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"16Rnd_9x21_Mag",
			"SmokeShell",
			"SmokeShell",
			"ADFRC_F1_GRENADE",
			"ADFRC_F1_GRENADE"
		};
		respawnMagazines[]={
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"16Rnd_9x21_Mag",
			"SmokeShell",
			"SmokeShell",
			"ADFRC_F1_GRENADE",
			"ADFRC_F1_GRENADE"
		};
		linkedItems[]={
			"adfrc_opscore_marine_Snakeskin_amcu_Ct_1_Aus",
			"ADFRC_PC_Tan_1",
			"adfrc_facewear_ESS_1",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
		respawnLinkedItems[]={
			"adfrc_opscore_marine_Snakeskin_amcu_Ct_1_Aus",
			"ADFRC_PC_Tan_1",
			"adfrc_facewear_ESS_1",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
	};
	class ADFRC_MD_AMCU_Support_UAV: ADFRC_MD_AMCU_Soldier_Base{
		displayName="UAV Operator";
		author="$STR_ADF_AUTHOR";
		scope=2;
		scopeCurator=2;
		editorPreview = "\ADF_Units\data\editorPreviews\MD\AMCU_Support_UAV.jpg";
		role="SpecialOperative";
		uavHacker=1;
		//threat[]={0.80000001,0.1,0.1}; <---For us to tweak the threat it poses to other units https://community.bistudio.com/wiki/CfgVehicles_Config_Reference#threat
		backpack="B_UAV_01_backpack_F";
		weapons[]={
			"arifle_AUG_black_arco_flash_F",
			"ADFRC_hpII",
			"Throw",
			"Put"
		};
		respawnWeapons[]={
			"arifle_AUG_black_arco_flash_F",
			"ADFRC_hpII",
			"Throw",
			"Put"
		};
		magazines[]={
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"16Rnd_9x21_Mag",
			"SmokeShell",
			"SmokeShell",
			"ADFRC_F1_GRENADE",
			"ADFRC_F1_GRENADE"
		};
		respawnMagazines[]={
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"16Rnd_9x21_Mag",
			"SmokeShell",
			"SmokeShell",
			"ADFRC_F1_GRENADE",
			"ADFRC_F1_GRENADE"
		};
		linkedItems[]={
			"adfrc_opscore_marine_Snakeskin_amcu_Ct_1_Aus",
			"ADFRC_PC_Tan_1",
			"adfrc_facewear_ESS_1",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"B_UavTerminal"
		};
		respawnLinkedItems[]={
			"adfrc_opscore_marine_Snakeskin_amcu_Ct_1_Aus",
			"ADFRC_PC_Tan_1",
			"adfrc_facewear_ESS_1",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"B_UavTerminal"
		};
	};
	////////////////////////Recon Units/////////////////////////////////////////////////////////////
	class ADFRC_MD_AMCU_Recon_F: ADFRC_MD_AMCU_Recon_Base{
		displayName="Recon Scout";
		author="$STR_ADF_AUTHOR";
		scope=2;
		scopeCurator=2;
		editorPreview = "\ADF_Units\data\editorPreviews\MD\AMCU_Recon_F.jpg";
		role="Rifleman";
		//threat[]={0.80000001,0.1,0.1}; <---For us to tweak the threat it poses to other units https://community.bistudio.com/wiki/CfgVehicles_Config_Reference#threat
		//backpack="ADFRC_Kitbag_AMCU";
		weapons[]={
			"arifle_AUG_black_arco_flash_F",
			"ADFRC_hpII",
			"Throw",
			"Put"
		};
		respawnWeapons[]={
			"arifle_AUG_black_arco_flash_F",
			"ADFRC_hpII",
			"Throw",
			"Put"
		};
		magazines[]={
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"16Rnd_9x21_Mag",
			"SmokeShell",
			"SmokeShell",
			"ADFRC_F1_GRENADE",
			"ADFRC_F1_GRENADE"
		};
		respawnMagazines[]={
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"16Rnd_9x21_Mag",
			"SmokeShell",
			"SmokeShell",
			"ADFRC_F1_GRENADE",
			"ADFRC_F1_GRENADE"
		};
		linkedItems[]={
			"adfrc_opscore_marine_Snakeskin_amcu_Ct_1_Aus",
			"ADFRC_PC_Tan_1",
			"adfrc_facewear_ESS_1",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
		respawnLinkedItems[]={
			"adfrc_opscore_marine_Snakeskin_amcu_Ct_1_Aus",
			"ADFRC_PC_Tan_1",
			"adfrc_facewear_ESS_1",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
	};
	class ADFRC_MD_AMCU_Recon_TL: ADFRC_MD_AMCU_Recon_Base{
		displayName="Recon Team Leader";
		author="$STR_ADF_AUTHOR";
		scope=2;
		scopeCurator=2;
		editorPreview = "\ADF_Units\data\editorPreviews\MD\AMCU_Recon_TL.jpg";
		icon="iconManLeader";
		role="Rifleman";
		cost=250000;
		//threat[]={0.80000001,0.1,0.1}; <---For us to tweak the threat it poses to other units https://community.bistudio.com/wiki/CfgVehicles_Config_Reference#threat
		//backpack="ADFRC_Kitbag_AMCU";
		weapons[]={
			"arifle_AUG_black_arco_flash_F",
			"ADFRC_hpII",
			"Throw",
			"Put"
		};
		respawnWeapons[]={
			"arifle_AUG_black_arco_flash_F",
			"ADFRC_hpII",
			"Throw",
			"Put"
		};
		magazines[]={
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"16Rnd_9x21_Mag",
			"SmokeShell",
			"SmokeShell",
			"ADFRC_F1_GRENADE",
			"ADFRC_F1_GRENADE"
		};
		respawnMagazines[]={
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"16Rnd_9x21_Mag",
			"SmokeShell",
			"SmokeShell",
			"ADFRC_F1_GRENADE",
			"ADFRC_F1_GRENADE"
		};
		linkedItems[]={
			"adfrc_opscore_marine_Snakeskin_amcu_Ct_1_Aus",
			"ADFRC_PC_Tan_1",
			"adfrc_facewear_ESS_1",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
		respawnLinkedItems[]={
			"adfrc_opscore_marine_Snakeskin_amcu_Ct_1_Aus",
			"ADFRC_PC_Tan_1",
			"adfrc_facewear_ESS_1",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
	};
	class ADFRC_MD_AMCU_Recon_CFA: ADFRC_MD_AMCU_Recon_Base{
		displayName="Recon Combat First Aider";
		author="$STR_ADF_AUTHOR";
		scope=2;
		scopeCurator=2;
		editorPreview = "\ADF_Units\data\editorPreviews\MD\AMCU_Recon_CFA.jpg";
		icon="iconManMedic";
		role="CombatLifeSaver";
		picture="pictureHeal";
		attendant=1;
		camouflage=1.6;
		//threat[]={0.80000001,0.1,0.1}; <---For us to tweak the threat it poses to other units https://community.bistudio.com/wiki/CfgVehicles_Config_Reference#threat 
		//backpack="ADFRC_Kitbag_AMCU";
		weapons[]={
			"arifle_AUG_black_arco_flash_F",
			"ADFRC_hpII",
			"Throw",
			"Put"
		};
		respawnWeapons[]={
			"arifle_AUG_black_arco_flash_F",
			"ADFRC_hpII",
			"Throw",
			"Put"
		};
		magazines[]={
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"16Rnd_9x21_Mag",
			"SmokeShell",
			"SmokeShell",
			"ADFRC_F1_GRENADE",
			"ADFRC_F1_GRENADE"
		};
		respawnMagazines[]={
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"16Rnd_9x21_Mag",
			"SmokeShell",
			"SmokeShell",
			"ADFRC_F1_GRENADE",
			"ADFRC_F1_GRENADE"
		};
		linkedItems[]={
			"adfrc_opscore_marine_Snakeskin_amcu_Ct_1_Aus",
			"ADFRC_PC_Tan_1",
			"adfrc_facewear_ESS_1",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
		respawnLinkedItems[]={
			"adfrc_opscore_marine_Snakeskin_amcu_Ct_1_Aus",
			"ADFRC_PC_Tan_1",
			"adfrc_facewear_ESS_1",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
	};
	class ADFRC_MD_AMCU_Recon_LSW: ADFRC_MD_AMCU_Recon_Base{
		displayName="Recon LSW Gunner";
		author="$STR_ADF_AUTHOR";
		scope=2;
		scopeCurator=2;
		editorPreview = "\ADF_Units\data\editorPreviews\MD\AMCU_Recon_LSW.jpg";
		icon="iconManMG";
		role="MachineGunner";
		cost=220000;
		//threat[]={0.80000001,0.1,0.1}; <---For us to tweak the threat it poses to other units https://community.bistudio.com/wiki/CfgVehicles_Config_Reference#threat 
		//backpack="ADFRC_Kitbag_AMCU";
		weapons[]={
			"arifle_AUG_black_arco_flash_F",
			"ADFRC_hpII",
			"Throw",
			"Put"
		};
		respawnWeapons[]={
			"arifle_AUG_black_arco_flash_F",
			"ADFRC_hpII",
			"Throw",
			"Put"
		};
		magazines[]={
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"16Rnd_9x21_Mag",
			"SmokeShell",
			"SmokeShell",
			"ADFRC_F1_GRENADE",
			"ADFRC_F1_GRENADE"
		};
		respawnMagazines[]={
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"16Rnd_9x21_Mag",
			"SmokeShell",
			"SmokeShell",
			"ADFRC_F1_GRENADE",
			"ADFRC_F1_GRENADE"
		};
		linkedItems[]={
			"adfrc_opscore_marine_Snakeskin_amcu_Ct_1_Aus",
			"ADFRC_PC_Tan_1",
			"adfrc_facewear_ESS_1",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
		respawnLinkedItems[]={
			"adfrc_opscore_marine_Snakeskin_amcu_Ct_1_Aus",
			"ADFRC_PC_Tan_1",
			"adfrc_facewear_ESS_1",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
	};
	class ADFRC_MD_AMCU_Recon_Sniper_MRSASS: ADFRC_MD_AMCU_Sniper_Temperate_Base{
		displayName="Sniper (SR-25)";
		author="$STR_ADF_AUTHOR";
		scope=1;
		scopeCurator=1;
		editorPreview = "\ADF_Units\data\editorPreviews\MD\AMCU_Recon_Sniper_MRSASS.jpg";
		role="Marksman";
		cost=250000;
		threat[]={0.80000001,0.30000001,0.30000001};
		//backpack="ADFRC_Kitbag_AMCU";
		weapons[]={
			"arifle_AUG_black_arco_flash_F",
			"ADFRC_hpII",
			"Throw",
			"Put"
		};
		respawnWeapons[]={
			"arifle_AUG_black_arco_flash_F",
			"ADFRC_hpII",
			"Throw",
			"Put"
		};
		magazines[]={
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"16Rnd_9x21_Mag",
			"SmokeShell",
			"SmokeShell",
			"ADFRC_F1_GRENADE",
			"ADFRC_F1_GRENADE"
		};
		respawnMagazines[]={
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"16Rnd_9x21_Mag",
			"SmokeShell",
			"SmokeShell",
			"ADFRC_F1_GRENADE",
			"ADFRC_F1_GRENADE"
		};
		linkedItems[]={
			"adfrc_opscore_marine_Snakeskin_amcu_Ct_1_Aus",
			"ADFRC_PC_Tan_1",
			"adfrc_facewear_ESS_1",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
		respawnLinkedItems[]={
			"adfrc_opscore_marine_Snakeskin_amcu_Ct_1_Aus",
			"ADFRC_PC_Tan_1",
			"adfrc_facewear_ESS_1",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
	};
	class ADFRC_MD_AMCU_Recon_Sniper: ADFRC_MD_AMCU_Sniper_Temperate_Base{
		displayName="Sniper (SR-98)";
		author="$STR_ADF_AUTHOR";
		scope=2;
		scopeCurator=2;
		editorPreview = "\ADF_Units\data\editorPreviews\MD\AMCU_Recon_Sniper.jpg";
		role="Marksman";
		cost=250000;
		threat[]={0.80000001,0.30000001,0.30000001};
		//backpack="ADFRC_Kitbag_AMCU";
		weapons[]={
			"arifle_AUG_black_arco_flash_F",
			"ADFRC_hpII",
			"Throw",
			"Put"
		};
		respawnWeapons[]={
			"arifle_AUG_black_arco_flash_F",
			"ADFRC_hpII",
			"Throw",
			"Put"
		};
		magazines[]={
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"16Rnd_9x21_Mag",
			"SmokeShell",
			"SmokeShell",
			"ADFRC_F1_GRENADE",
			"ADFRC_F1_GRENADE"
		};
		respawnMagazines[]={
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"16Rnd_9x21_Mag",
			"SmokeShell",
			"SmokeShell",
			"ADFRC_F1_GRENADE",
			"ADFRC_F1_GRENADE"
		};
		linkedItems[]={
			"adfrc_opscore_marine_Snakeskin_amcu_Ct_1_Aus",
			"ADFRC_PC_Tan_1",
			"adfrc_facewear_ESS_1",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
		respawnLinkedItems[]={
			"adfrc_opscore_marine_Snakeskin_amcu_Ct_1_Aus",
			"ADFRC_PC_Tan_1",
			"adfrc_facewear_ESS_1",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
	};
	class ADFRC_MD_AMCU_Recon_Sniper_LRAP: ADFRC_MD_AMCU_Sniper_Temperate_Base{
		displayName="Sniper (Blaser)";
		author="$STR_ADF_AUTHOR";
		scope=1;
		scopeCurator=1;
		editorPreview = "\ADF_Units\data\editorPreviews\MD\AMCU_Recon_Sniper_LRAP.jpg";
		role="Marksman";
		cost=250000;
		threat[]={0.80000001,0.30000001,0.30000001};
		//backpack="ADFRC_Kitbag_AMCU";
		weapons[]={
			"arifle_AUG_black_arco_flash_F",
			"ADFRC_hpII",
			"Throw",
			"Put"
		};
		respawnWeapons[]={
			"arifle_AUG_black_arco_flash_F",
			"ADFRC_hpII",
			"Throw",
			"Put"
		};
		magazines[]={
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"16Rnd_9x21_Mag",
			"SmokeShell",
			"SmokeShell",
			"ADFRC_F1_GRENADE",
			"ADFRC_F1_GRENADE"
		};
		respawnMagazines[]={
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"16Rnd_9x21_Mag",
			"SmokeShell",
			"SmokeShell",
			"ADFRC_F1_GRENADE",
			"ADFRC_F1_GRENADE"
		};
		linkedItems[]={
			"adfrc_opscore_marine_Snakeskin_amcu_Ct_1_Aus",
			"ADFRC_PC_Tan_1",
			"adfrc_facewear_ESS_1",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
		respawnLinkedItems[]={
			"adfrc_opscore_marine_Snakeskin_amcu_Ct_1_Aus",
			"ADFRC_PC_Tan_1",
			"adfrc_facewear_ESS_1",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
	};
	class ADFRC_MD_AMCU_Recon_Sniper_AM: ADFRC_MD_AMCU_Sniper_Temperate_Base{
		displayName="Sniper (AW50F)";
		author="$STR_ADF_AUTHOR";
		scope=2;
		scopeCurator=2;
		editorPreview = "\ADF_Units\data\editorPreviews\MD\AMCU_Recon_Sniper_AM.jpg";
		role="Marksman";
		cost=250000;
		threat[]={0.80000001,0.30000001,0.30000001};
		//backpack="ADFRC_Kitbag_AMCU";
		weapons[]={
			"arifle_AUG_black_arco_flash_F",
			"ADFRC_hpII",
			"Throw",
			"Put"
		};
		respawnWeapons[]={
			"arifle_AUG_black_arco_flash_F",
			"ADFRC_hpII",
			"Throw",
			"Put"
		};
		magazines[]={
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"16Rnd_9x21_Mag",
			"SmokeShell",
			"SmokeShell",
			"ADFRC_F1_GRENADE",
			"ADFRC_F1_GRENADE"
		};
		respawnMagazines[]={
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"16Rnd_9x21_Mag",
			"SmokeShell",
			"SmokeShell",
			"ADFRC_F1_GRENADE",
			"ADFRC_F1_GRENADE"
		};
		linkedItems[]={
			"adfrc_opscore_marine_Snakeskin_amcu_Ct_1_Aus",
			"ADFRC_PC_Tan_1",
			"adfrc_facewear_ESS_1",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
		respawnLinkedItems[]={
			"adfrc_opscore_marine_Snakeskin_amcu_Ct_1_Aus",
			"ADFRC_PC_Tan_1",
			"adfrc_facewear_ESS_1",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
	};
	////////////////////////BACKPACKS///////////////////////////////////////////////////////////////
	class ADFRC_AssaultPack_AMCU;
	class ADFRC_CarryAll_AMCU;
	class ADFRC_CarryAll_AMCU_MED;
	class ADFRC_AssaultPack_AMCU_TL: ADFRC_AssaultPack_AMCU{
		scope=1;
		author=$STR_ADF_AUTHOR;
		class TransportMagazines{
			class _xx_1Rnd_HE_Grenade_shell{
				magazine="1Rnd_HE_Grenade_shell";
				count=10;
			};
			class _xx_UGL_FlareGreen_F{
				magazine="UGL_FlareGreen_F";
				count=2;
			};
			class _xx_1Rnd_Smoke_Grenade_shell{
				magazine="1Rnd_Smoke_Grenade_shell";
				count=4;
			};
			class _xx_1Rnd_SmokeRed_Grenade_shell{
				magazine="1Rnd_SmokeRed_Grenade_shell";
				count=4;
			};
			class _xx_1Rnd_SmokeOrange_Grenade_shell{
				magazine="1Rnd_SmokeOrange_Grenade_shell";
				count=2;
			};
			class _xx_1Rnd_SmokeBlue_Grenade_shell{
				magazine="1Rnd_SmokeBlue_Grenade_shell";
				count=2;
			};
		};
	};
	class ADFRC_CarryAll_AMCU_LMG: ADFRC_CarryAll_AMCU{
		scope=1;
		author=$STR_ADF_AUTHOR;
		class TransportItems{
			class _xx_ADFRC_booniehat_AMCU{
				name="ADFRC_booniehat_AMCU";
				count=1;
			};
		};
		class TransportMagazines{
			class _xx_ADFRC_200Rnd_556_Belt_TR5{
				magazine="ADFRC_200Rnd_556_Belt_TR5";
				count=2;
			};
		};
	};
	class ADFRC_CarryAll_AMCU_MMG: ADFRC_CarryAll_AMCU{
		scope=1;
		author=$STR_ADF_AUTHOR;
		class TransportItems{
			class _xx_ADFRC_booniehat_AMCU{
				name="ADFRC_booniehat_AMCU";
				count=1;
			};
		};
		class TransportMagazines{
			class _xx_ADFRC_200Rnd_556_Belt_TR5{
				magazine="ADFRC_200Rnd_556_Belt_TR5";
				count=2;
			};
		};
	};
	class ADFRC_CarryAll_AMCU_GSMG: ADFRC_CarryAll_AMCU{
		scope=1;
		author=$STR_ADF_AUTHOR;
		class TransportItems{
			class _xx_ADFRC_booniehat_AMCU{
				name="ADFRC_booniehat_AMCU";
				count=1;
			};
		};
		class TransportMagazines{
			class _xx_ADFRC_150Rnd_762_Belt_TR5{
				magazine="ADFRC_150Rnd_762_Belt_TR5";
				count=4;
			};
		};
	};
	class ADFRC_CarryAll_AMCU_AB: ADFRC_CarryAll_AMCU{
		scope=1;
		author=$STR_ADF_AUTHOR;
		class TransportItems{
			class _xx_ADFRC_booniehat_AMCU{
				name="ADFRC_booniehat_AMCU";
				count=1;
			};
		};
		class TransportMagazines{
			class _xx_ADFRC_200Rnd_556_Belt_TR5{
				magazine="ADFRC_200Rnd_556_Belt_TR5";
				count=2;
			};
		};
	};
	class ADFRC_CarryAll_AMCU_Diver: ADFRC_CarryAll_AMCU{
		scope=1;
		author=$STR_ADF_AUTHOR;
		class TransportItems{
			class _xx_adfrc_ECH_AMCU{
				name="adfrc_ECH_AMCU";
				count=1;
			};
			class _xx_ADFRC_booniehat_AMCU{
				name="ADFRC_booniehat_AMCU";
				count=1;
			};
			class _xx_ADFRC_carrierLite_AMCU{
				name="ADFRC_carrierLite_AMCU";
				count=1;
			};
			class _xx_ADFRC_uniform_AMCU{
				name="ADFRC_uniform_AMCU";
				count=1;
			};
		};
	};
	class ADFRC_CarryAll_AMCU_Engineer: ADFRC_CarryAll_AMCU{
		scope=1;
		author=$STR_ADF_AUTHOR;
		class TransportItems{
			class _xx_ADFRC_booniehat_AMCU{
				name="ADFRC_booniehat_AMCU";
				count=1;
			};
			class _xx_MineDetector{
				name="MineDetector";
				count=1;
			};
			class _xx_DemoCharge_Remote_Mag{
				name="DemoCharge_Remote_Mag";
				count=2;
			};
			class _xx_Toolkit{
				name="Toolkit";
				count=1;
			};
		};
	};
	class ADFRC_CarryAll_AMCU_Mine: ADFRC_CarryAll_AMCU{
		scope=1;
		author=$STR_ADF_AUTHOR;
		class TransportItems{
			class _xx_ADFRC_booniehat_AMCU{
				name="ADFRC_booniehat_AMCU";
				count=1;
			};
			class _xx_MineDetector{
				name="MineDetector";
				count=1;
			};
			class _xx_DemoCharge_Remote_Mag{
				name="DemoCharge_Remote_Mag";
				count=2;
			};
			class _xx_Toolkit{
				name="Toolkit";
				count=1;
			};
		};
	};
	class ADFRC_CarryAll_AMCU_HAT: ADFRC_CarryAll_AMCU{
		scope=1;
		author=$STR_ADF_AUTHOR;
		class TransportItems{
			class _xx_ADFRC_booniehat_AMCU{
				name="ADFRC_booniehat_AMCU";
				count=1;
			};
		};
		class TransportMagazines{
			class _xx_ADFRC_magazine_84mm_hedp_502{
				magazine="ADFRC_magazine_84mm_hedp_502";
				count=1;
			};
			class _xx_ADFRC_magazine_84mm_heat_751{
				magazine="ADFRC_magazine_84mm_heat_551c";
				count=1;
			};
		};
	};
	class ADFRC_CarryAll_AMCU_MAT: ADFRC_CarryAll_AMCU{
		scope=1;
		author=$STR_ADF_AUTHOR;
		class TransportItems{
			class _xx_ADFRC_booniehat_AMCU{
				name="ADFRC_booniehat_AMCU";
				count=1;
			};
		};
		class TransportMagazines{
			class _xx_ADFRC_magazine_84mm_hedp_502{
				magazine="ADFRC_magazine_84mm_hedp_502";
				count=1;
			};
			class _xx_ADFRC_magazine_84mm_heat_751{
				magazine="ADFRC_magazine_84mm_heat_551c";
				count=1;
			};
		};
	};
	class ADFRC_CarryAll_AMCU_GL: ADFRC_CarryAll_AMCU{
		scope=1;
		author=$STR_ADF_AUTHOR;
		class TransportItems{
			class _xx_ADFRC_booniehat_AMCU{
				name="ADFRC_booniehat_AMCU";
				count=1;
			};
			class _xx_SmokeShell{
				name="SmokeShell";
				count=2;
			};
		};
		class TransportMagazines{
			class _xx_1Rnd_HE_Grenade_shell{
				magazine="1Rnd_HE_Grenade_shell";
				count=15;
			};
			class _xx_ADFRC_F1_GRENADE{
				magazine="ADFRC_F1_GRENADE";
				count=2;
			};
			class _xx_UGL_FlareGreen_F{
				magazine="UGL_FlareGreen_F";
				count=2;
			};
			class _xx_1Rnd_Smoke_Grenade_shell{
				magazine="1Rnd_Smoke_Grenade_shell";
				count=4;
			};
		};
	};
	class ADFRC_CarryAll_AMCU_MED_CFA: ADFRC_CarryAll_AMCU_MED{
		author="$STR_ADF_AUTHOR";
		scope=1;
		class TransportItems{
			class _xx_Medikit{
				name="Medikit";
				count=1;
			};
			class _xx_FirstAidKit{
				name="FirstAidKit";
				count=10;
			};
		};
	};
	////////////////////////////////////////////////////////////////////////////////////////////////
	class ADFRC_MD_MTS_CD_Base;
	class ADFRC_MD_MTS_CD_Rolled_Base;
	class ADFRC_MD_MTS_CD_Tee_Base;
	class ADFRC_MD_MTS_CD_Diver_Base;
	class ADFRC_MD_Green_TAG_Base;
	class ADFRC_MD_Green_TAG_Rolled_Base;
	class ADFRC_MD_MC_SASR_Base;
	class ADFRC_MD_MC_SASR_Rolled_Base;
	class ADFRC_MD_MC_SASR_Tee_Base;
	class ADFRC_MD_SASR_Sniper_Temperate_Base;
	class ADFRC_MD_SASR_Sniper_Tropical_Base;
	class ADFRC_MD_SASR_Sniper_Arid_Base;
